#!/bin/bash
#SBATCH --job-name=mnist_quantum_hydra_s2026
#SBATCH --account=m4138_g
#SBATCH --constraint=gpu&hbm80g
#SBATCH --qos=shared
#SBATCH -t 48:00:00
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --cpus-per-task=32
#SBATCH --output=/pscratch/sd/j/junghoon/quantum_hydra_mamba/results/mnist_results/logs/mnist_quantum_hydra_seed2026.log
#SBATCH --error=/pscratch/sd/j/junghoon/quantum_hydra_mamba/results/mnist_results/logs/mnist_quantum_hydra_seed2026.log

# Job script for MNIST Classification: quantum_hydra (seed=2026)
# Auto-generated by generate_mnist_job_scripts.py

# Activate conda environment
source /pscratch/sd/j/junghoon/.bashrc
conda activate /pscratch/sd/j/junghoon/conda-envs/qml_eeg

# Change to project directory
cd /pscratch/sd/j/junghoon/quantum_hydra_mamba

# Run training
python scripts/run_single_model_mnist.py \
    --model-name quantum_hydra \
    --n-qubits 6 \
    --qlcu-layers 2 \
    --d-model 128 \
    --d-state 16 \
    --n-epochs 50 \
    --batch-size 32 \
    --lr 0.001 \
    --n-train 500 \
    --n-valtest 250 \
    --early-stopping-patience 10 \
    --seed 2026 \
    --output-dir ./results/mnist_results \
    --device cuda

echo "Job completed: quantum_hydra seed=2026"
