#!/bin/bash
#SBATCH --job-name=dna_quantum_mamba_s2028
#SBATCH --account=m4138_g
#SBATCH --constraint=gpu&hbm80g
#SBATCH --qos=shared
#SBATCH -t 48:00:00
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --cpus-per-task=32
#SBATCH --output=/pscratch/sd/j/junghoon/quantum_hydra_mamba/results/dna_results/logs/dna_quantum_mamba_seed2028.log
#SBATCH --error=/pscratch/sd/j/junghoon/quantum_hydra_mamba/results/dna_results/logs/dna_quantum_mamba_seed2028.log

# Job script for DNA Sequence Classification: quantum_mamba (seed=2028)
# Auto-generated by generate_dna_job_scripts.py

# Activate conda environment
source /pscratch/sd/j/junghoon/.bashrc
conda activate /pscratch/sd/j/junghoon/conda-envs/qml_eeg

# Change to project directory
cd /pscratch/sd/j/junghoon/quantum_hydra_mamba

# Run training
python scripts/run_single_model_dna.py \
    --model-name quantum_mamba \
    --n-qubits 6 \
    --qlcu-layers 2 \
    --d-model 128 \
    --d-state 16 \
    --n-epochs 50 \
    --batch-size 32 \
    --lr 0.001 \
    --early-stopping-patience 10 \
    --n-train 100 \
    --n-valtest 50 \
    --encoding onehot \
    --seed 2028 \
    --output-dir ./results/dna_results \
    --device cuda

echo "Job completed: quantum_mamba seed=2028"
